<a href="https://colab.research.google.com/github/haramkim1003-uxu/-1/blob/main/250419_Pandas%EB%AA%A8%EB%93%88%EC%9D%98_%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {'name': ['Pororo ','Krong','Pobi','Edie','Rupi'], 'Kor':[90,80,90,100,70],'math':[60,90,80,50,90],'science':[70,50,50,80,85],'art':[60,30,90,80,70],'social':[80,40,95,75,60],'English':[10,0,80,100,30]}

In [ ]:
data

{'name': ['Pororo ', 'Krong', 'Pobi', 'Edie', 'Rupi'],
 'Kor': [90, 80, 90, 100, 70],
 'math': [60, 90, 80, 50, 90],
 'science': [70, 50, 50, 80, 85],
 'art': [60, 30, 90, 80, 70],
 'social': [80, 40, 95, 75, 60],
 'English': [10, 0, 80, 100, 30]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

      name  Kor  math  science  art  social  English
0  Pororo    90    60       70   60      80       10
1    Krong   80    90       50   30      40        0
2     Pobi   90    80       50   90      95       80
3     Edie  100    50       80   80      75      100
4     Rupi   70    90       85   70      60       30

In [ ]:
df.head()

      name  Kor  math  science  art  social  English
0  Pororo    90    60       70   60      80       10
1    Krong   80    90       50   30      40        0
2     Pobi   90    80       50   90      95       80
3     Edie  100    50       80   80      75      100
4     Rupi   70    90       85   70      60       30

In [ ]:
df.head(2)

      name  Kor  math  science  art  social  English
0  Pororo    90    60       70   60      80       10
1    Krong   80    90       50   30      40        0

In [ ]:
df.tail()

      name  Kor  math  science  art  social  English
0  Pororo    90    60       70   60      80       10
1    Krong   80    90       50   30      40        0
2     Pobi   90    80       50   90      95       80
3     Edie  100    50       80   80      75      100
4     Rupi   70    90       85   70      60       30

In [ ]:
df.tail(2)

   name  Kor  math  science  art  social  English
3  Edie  100    50       80   80      75      100
4  Rupi   70    90       85   70      60       30

from matplotlib import pyplot as plt
_df_0['Kor'].plot(kind='hist', bins=20, title='Kor')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['math'].plot(kind='hist', bins=20, title='math')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['science'].plot(kind='hist', bins=20, title='science')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['art'].plot(kind='hist', bins=20, title='art')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Kor', y='math', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='math', y='science', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='science', y='art', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='art', y='social', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['math']
  ys = series['Kor']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('math', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('name')):
  _plot_series(series, series_name, i)
  fig.legend(title='name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('math')
_ = plt.ylabel('Kor')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['math']
  ys = series['art']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('math', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('name')):
  _plot_series(series, series_name, i)
  fig.legend(title='name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('math')
_ = plt.ylabel('art')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['math']
  ys = series['social']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('math', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('name')):
  _plot_series(series, series_name, i)
  fig.legend(title='name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('math')
_ = plt.ylabel('social')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['math']
  ys = series['English']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('math', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('name')):
  _plot_series(series, series_name, i)
  fig.legend(title='name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('math')
_ = plt.ylabel('English')

from matplotlib import pyplot as plt
_df_13['Kor'].plot(kind='line', figsize=(8, 4), title='Kor')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['math'].plot(kind='line', figsize=(8, 4), title='math')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['science'].plot(kind='line', figsize=(8, 4), title='science')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['art'].plot(kind='line', figsize=(8, 4), title='art')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='Kor', y='name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='math', y='name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='science', y='name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='art', y='name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.columns

Index(['name', 'Kor', 'math', 'science', 'art', 'social', 'English'], dtype='object')

In [ ]:
df2 = pd.DataFrame(data, columns=['math', 'Kor', 'science','art','social','English'], index=['one', 'two', 'three', 'four', 'five'])

In [ ]:
df2

       math  Kor  science  art  social  English
one      60   90       70   60      80       10
two      90   80       50   30      40        0
three    80   90       50   90      95       80
four     50  100       80   80      75      100
five     90   70       85   70      60       30

In [ ]:
#기술 통게분석:descriptive analaysis /개수, 평균, 중간값, 표준편차
df2.describe()
df2.describe()

            math         Kor    science        art     social     English
count   5.000000    5.000000   5.000000   5.000000   5.000000    5.000000
mean   74.000000   86.000000  67.000000  66.000000  70.000000   44.000000
std    18.165902   11.401754  16.431677  23.021729  20.916501   43.931765
min    50.000000   70.000000  50.000000  30.000000  40.000000    0.000000
25%    60.000000   80.000000  50.000000  60.000000  60.000000   10.000000
50%    80.000000   90.000000  70.000000  70.000000  75.000000   30.000000
75%    90.000000   90.000000  80.000000  80.000000  80.000000   80.000000
max    90.000000  100.000000  85.000000  90.000000  95.000000  100.000000

In [ ]:
df2.count()

math       5
Kor        5
science    5
art        5
social     5
English    5
dtype: int64

In [ ]:
df2.mean()

math       74.0
Kor        86.0
science    67.0
art        66.0
social     70.0
English    44.0
dtype: float64

In [ ]:
df3 = pd.DataFrame(data, columns=['kor', 'name', 'math', 'science', 'music'], index=['one', 'two', 'three', 'four', 'five'])

In [ ]:
df3

       kor     name  math  science music
one    NaN  Pororo     60       70   NaN
two    NaN    Krong    90       50   NaN
three  NaN     Pobi    80       50   NaN
four   NaN     Edie    50       80   NaN
five   NaN     Rupi    90       85   NaN

In [ ]:
df3['music'] = 25

In [ ]:
df3

       kor     name  math  science  music
one    NaN  Pororo     60       70     25
two    NaN    Krong    90       50     25
three  NaN     Pobi    80       50     25
four   NaN     Edie    50       80     25
five   NaN     Rupi    90       85     25

In [ ]:
df3['music'] = [20,10,30,50,25]

In [ ]:
df3

       kor     name  math  science  music
one    NaN  Pororo     60       70     20
two    NaN    Krong    90       50     10
three  NaN     Pobi    80       50     30
four   NaN     Edie    50       80     50
five   NaN     Rupi    90       85     25

In [ ]:
df4 = df3.drop('music',axis = 1)

In [ ]:
df4

       kor     name  math  science
one    NaN  Pororo     60       70
two    NaN    Krong    90       50
three  NaN     Pobi    80       50
four   NaN     Edie    50       80
five   NaN     Rupi    90       85

In [ ]:
df4.index.name = 'Order'

In [ ]:
df4

       kor     name  math  science
Order
one    NaN  Pororo     60       70
two    NaN    Krong    90       50
three  NaN     Pobi    80       50
four   NaN     Edie    50       80
five   NaN     Rupi    90       85

In [ ]:
df4.columns.name = 'subject'

In [ ]:
df4

subject  kor     name  math  science
Order
one      NaN  Pororo     60       70
two      NaN    Krong    90       50
three    NaN     Pobi    80       50
four     NaN     Edie    50       80
five     NaN     Rupi    90       85

In [ ]:
df5 = df4.loc['two':'four','name':'science']

In [ ]:
df5

subject   name  math  science
Order
two      Krong    90       50
three     Pobi    80       50
four      Edie    50       80

In [ ]:
df4

subject  kor     name  math  science
Order
one      NaN  Pororo     60       70
two      NaN    Krong    90       50
three    NaN     Pobi    80       50
four     NaN     Edie    50       80
five     NaN     Rupi    90       85

In [ ]:
df6 = df4.iloc[1:4,1:4]

In [ ]:
df6

subject   name  math  science
Order
two      Krong    90       50
three     Pobi    80       50
four      Edie    50       80

In [ ]:
df7 = df4.loc[df4['name'] == 'Pororo',['name','math','science']]

NameError: name 'df4' is not defined

In [ ]:
df7

NameError: name 'df7' is not defined

In [ ]:
import pandas as pd

In [ ]:
timetable = {'period': ['1st period','2nd period','3rd period','4th period','5th period','6th period','7th period'], 'mon':[morality,math,science,technology,Korean,history,doesnot exist],'tue':[history,P.E,math,home,Chinese characters,English,Korean],'wen':[P.E,Korean,English,Chinese characters,history,morality,doesnot exist],'thu':[math,technology,Korean,history,P.E,Korean,home],'fri':[morality,history,English,math,Korean,science,doesnot exist]}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-35-5681bd36e292>, line 1)

In [ ]:
timetable

       mon  tue  wen  thu  fri
one    NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  NaN  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN
four   NaN  NaN  NaN  NaN  NaN
five   NaN  NaN  NaN  NaN  NaN
six    NaN  NaN  NaN  NaN  NaN
seven  NaN  NaN  NaN  NaN  NaN

In [ ]:
timetable = timetable.loc['tue':'thu','2nd period':'5th period']

KeyError: '2nd period'

In [ ]:
timetable = pd.DataFrame(data, columns=['mon', 'tue', 'wen','thu','fri'], index=['one', 'two', 'three', 'four', 'five','six','seven'])

In [ ]:
timetable

       mon  tue  wen  thu  fri
one    NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  NaN  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN
four   NaN  NaN  NaN  NaN  NaN
five   NaN  NaN  NaN  NaN  NaN
six    NaN  NaN  NaN  NaN  NaN
seven  NaN  NaN  NaN  NaN  NaN

In [ ]:
timetabie.index.time= 'time'

NameError: name 'timetabie' is not defined

In [ ]:
timetabie

NameError: name 'timetabie' is not defined

In [ ]:
timetabie.columns.time = 'day'

NameError: name 'timetabie' is not defined

In [ ]:
timetabie

NameError: name 'timetabie' is not defined

In [ ]:
timetable.index.Time

In [ ]:
timetable =timetabie.loc['tue:2nd period':'thu:5th period','tue':'thu']

NameError: name 'timetabie' is not defined

In [ ]:
timetabie.index.name = time

NameError: name 'time' is not defined

In [ ]:
timetabie.columns.name = day

NameError: name 'day' is not defined

In [ ]:
My favorite subject = timetable.drop('mon,fri',axis = 1)

SyntaxError: invalid syntax (<ipython-input-57-70aa11058ac0>, line 1)